# * ********************************************************************************************************* *
# *
# * Copyright 2022 Michal Kelnar
# *
# * SPDX-License-Identifier: BSD-3-Clause
# * The BSD-3-Clause license for this file can be found in the LICENSE.txt file included with this distribution
# * or at https://spdx.org/licenses/BSD-3-Clause.html#licenseText
# *
# * ********************************************************************************************************* *
---
root: true

extends:
  - eslint:recommended

plugins:
  - import
  - async-await
  - promise

parserOptions:
  ecmaVersion: 2022
  sourceType: module

env:
  es6: true
